### ISSUE TITLE
GetContentFromUrl service does not fail requests to bad addresses

### ISSUE THREAD

**Issue by mcoquet** [nneves/UrlSearchEngine#2]
when you provide a fake request like `moo` instead of `www.botdream.com` the service responds with a 200 but the content reads `ENOENT`

I suggest It should forward whatever the upstream returns (404, 500, etc)

**Comment by nneves** [comment]
This is a tricky one, Request module is responding with this data:

* Successfully request  `curl http://localhost:6000/\?url\=www.botdream.com`
response and body properties contain data, error is undefined

```
response.statusCode => 200
response.statusMessage => OK
````
all good, I can forward this to the initial request!

* Bad request  `curl http://localhost:6000/\?url\=moo`

response and body properties are undefined, error contains data

```
error.code => ENOTFOUND
error.errno => ENOTFOUND
```

There is no http response.statusCode returned!!!




My suggestion, I will forward the successfully statusCode/statusMessage to the initial request call when things run normally without errors!

In case of some sort of error, I will return an hardcoded statusCode=500 and statusMessage=error.errno!

@mcoquet do you agree or have another idea ?

**Comment by nneves** [comment]
FYI: the above comment relates to this part of the code: https://github.com/nneves/UrlSearchEngine/blob/master/GetContentFromURL/content-as-a-service/lib/contentService.js#L32

**Comment by nneves** [comment]
@mcoquet submitted the PR to fix this, in case you agree with my solution!

**Comment by mcoquet** [comment]
sounds great :) ill have a look later tonight
