### ISSUE TITLE
think of a way to retrieve the page title and return it for the Title field

### ISSUE THREAD

**Issue by mcoquet** [nneves/UrlSearchEngine#4]
currently its always set to empty in SaveUrlToDb because there is no simple way to retrieve from GeContentFromUrl.

I suggest we make that service return the page title and the content as JSON:

`{ title:"Some Title", content: " this is the long string that represents the lorem ipsum of the page :D"}`

**Comment by nneves** [comment]
Fixed from PR: https://github.com/nneves/UrlSearchEngine/pull/6
