### ISSUE TITLE
Be more tolerant of different protocols in GetCotentFromUrl 

### ISSUE THREAD

**Issue by mcoquet** [nneves/UrlSearchEngine#7]
Currently if I send it an https address or even just include http in the address it tries to fetch http://http://xxx . It should avoid appending the protocol if one is provided.

**Comment by nneves** [comment]
Trying to replicate this and all seems to work fine, here are 3 scenarios:

1) explicit request http://
```
curl --silent http://localhost:6000/\?url\=http://www.google.pt/ | jq .
{
  "url": "http://www.google.pt/",
  "title": "Google",
  "content": "* Pesquisa..."
}
```

Service debug message:
> getcontentfromurl_1  | Get page content for url: http://www.google.pt/

2) explicit request https://
```
curl --silent http://localhost:6000/\?url\=https://www.google.pt/ | jq .
{
  "url": "https://www.google.pt/",
  "title": "Google",
  "content": "* Pesquisa..."
}
```

Service debug message:
> getcontentfromurl_1  | Get page content for url: https://www.google.pt/

3) do not send http(s) -> GetContentFromURL will default to http
```
curl --silent http://localhost:6000/\?url\=www.google.pt/ | jq .
{
  "url": "http://www.google.pt/",
  "title": "Google",
  "content": "* Pesquisa..."
}
```

Service debug message:
Get page content for url: http://www.google.pt/

From the sourcecode, here the URL is verified and http added if no protocol is defined:
https://github.com/nneves/UrlSearchEngine/blob/master/GetContentFromURL/content-as-a-service/routes/index.js#L17

Here is were the black magic happens: https://github.com/nneves/UrlSearchEngine/blob/master/GetContentFromURL/content-as-a-service/lib/utils.js#L19

So, from the GetContentFromURL service all seems to be working as expected, unless point 3) defaulting to http can cause issues in future! This will not work if no protocol is defined, so I really need to default to something or it crashes the request!
